osx_image: xcode8.3
language: swift

cache: cocoapods
podfile: Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=CWWeChat.xcworkspace
  matrix:
    - SCHEME="CWWeChat"

before_install:
  - gem install xcpretty --quiet
  - gem install cocoapods --quiet
  - pod repo update --verbose
  - pod install

script:
  - set -o pipefail
  - xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -configuration Debug clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c

after_success:
  - sleep 5
